<?php

use Illuminate\Database\Seeder;

class BBcodesTableSeeder extends Seeder {

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run () {


        \DB::table('bbcodes')->delete();
        \DB::table('bbcodes')->insert(array (
            array ('bbcodeId' => '1', 'name' => 'List', 'example' => '[li] Test Text 1[/li]', 'pattern' => '/\\[li\\](.*?)\\[\\/li\\]/si', 'replace' => '<li>$1</li>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '2', 'name' => 'Title', 'example' => '[atitle] Test Text 1[/atitle]', 'pattern' => '/\\[atitle\\](.*?)\\[\\/atitle\\]/si', 'replace' => '<div class="atitle">$1</div>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '3', 'name' => 'Ul list', 'example' => '[ul]Test Text 1[/ul]', 'pattern' => '/\\[ul\\](.*?)\\[\\/ul\\]/si', 'replace' => '<ul>$1</ul>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '4', 'name' => 'bold', 'example' => '[b]Bold[/b]', 'pattern' => '/\\[b\\](.*?)\\[\\/b\\]/si', 'replace' => '<strong>$1</strong>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '5', 'name' => 'italic', 'example' => '[i]Italic[/i]', 'pattern' => '/\\[i\\](.*?)\\[\\/i\\]/si', 'replace' => '<em>$1</em>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '6', 'name' => 'underline', 'example' => '[u]Underline[/u]', 'pattern' => '/\\[u\\](.*?)\\[\\/u\\]/si', 'replace' => '<u>$1</u>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '7', 'name' => 'linethrough', 'example' => '[s]Strike[/s]', 'pattern' => '/\\[s\\](.*?)\\[\\/s\\]/si', 'replace' => '<strike>$1</strike>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '8', 'name' => 'size', 'example' => '[size=3]Size[/size]', 'pattern' => '/\\[size\\=([1-7])\\](.*?)\\[\\/size\\]/si', 'replace' => '<font size="$1">$2</font>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '9', 'name' => 'Font Style', 'example' => '[font=Lucida Sans Unicode]Style[/font]', 'pattern' => '/\\[font\\=(.*?)\\](.*?)\\[\\/font\\]/si', 'replace' => '<font face="$1">$2</font>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '10', 'name' => 'table', 'example' => '[table]table[/table]', 'pattern' => '/\\[table\\](.*?)\\[\\/table\\]/si', 'replace' => '<table>$1</table>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '11', 'name' => 'tr', 'example' => '[tr]tr[/tr]', 'pattern' => '/\\[tr\\](.*?)\\[\\/tr\\]/si', 'replace' => '<tr>$1</tr>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '12', 'name' => 'td', 'example' => '[td]td[/td]', 'pattern' => '/\\[td\\](.*?)\\[\\/td\\]/si', 'replace' => '<td>$1</td>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '13', 'name' => 'center', 'example' => '[center]Center[/center]', 'pattern' => '/\\[center\\](.*?)\\[\\/center\\]/si', 'replace' => '<div style="text-align:center;">$1</div>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '14', 'name' => 'left', 'example' => '[left]Left[/left]', 'pattern' => '/\\[left\\](.*?)\\[\\/left\\]/si', 'replace' => '<div style="text-align:left;">$1</div>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '15', 'name' => 'right', 'example' => '[right]Right[/right]', 'pattern' => '/\\[right\\](.*?)\\[\\/right\\]/si', 'replace' => '<div style="text-align:right;">$1</div>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '16', 'name' => 'quotepost', 'example' => '[quotepost=5]Quote[/quotepost]', 'pattern' => '/\\[quotepost=(.*?)\\](.*?)\\[\\/quotepost\\]/si', 'replace' => '<div class="quotepost" data-post-id="$1">$2</div>', 'content' => '$2', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '17', 'name' => 'link', 'example' => '[url]http://google.com[/url]', 'pattern' => '/\\[url\\](.*?)\\[\\/url\\]/si', 'replace' => '<a target="_blank" href="$1" >$1</a>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '18', 'name' => 'namedlink', 'example' => '[url=http://google.com]Google[/url]', 'pattern' => '/\\[url\\=(.*?)\\](.*?)\\[\\/url\\]/si', 'replace' => '<a target="_blank" href="$1">$2</a>', 'content' => '$2', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '19', 'name' => 'color', 'example' => '[color=black]Black Color[/color]', 'pattern' => '/\\[color\\=(.*?)\\](.*?)\\[\\/color\\]/si', 'replace' => '<span style="color: $1;">$2</span>', 'content' => '$2', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '20', 'name' => 'image', 'example' => '[img]https://img.pokemondb.net/sprites/black-white/normal/pikachu.png[/img]', 'pattern' => '/\\[img\\](.*?)\\[\\/img\\]/si', 'replace' => '<img src="$1">', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '21', 'name' => 'image size', 'example' => '[img width=200,height=200]https://img.pokemondb.net/sprites/black-white/normal/pikachu.png[/img]', 'pattern' => '/\\[img width=(.*?),height=(.*?)\\](.*?)\\[\\/img\\]/si', 'replace' => '<img width="$1" height="$2" src="$3">', 'content' => '$3', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '22', 'name' => 'image left', 'example' => '[imgl]https://img.pokemondb.net/sprites/black-white/normal/pikachu.png[/imgl]', 'pattern' => '/\\[imgl\\](.*?)\\[\\/imgl\\]/si', 'replace' => '<img src="$1" align="left">', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '23', 'name' => 'image right', 'example' => '[imgr]https://img.pokemondb.net/sprites/black-white/normal/pikachu.png[/imgr]', 'pattern' => '/\\[imgr\\](.*?)\\[\\/imgr\\]/si', 'replace' => '<img src="$1" align="right">', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '24', 'name' => 'orderedlistnumerical', 'example' => '[list=1]Hey[/list]', 'pattern' => '/\\[list=1\\](.*?)\\[\\/list\\]/si', 'replace' => '<ol>$1</ol>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '25', 'name' => 'unorderedlist', 'example' => '[list]Hey[/list]', 'pattern' => '/\\[list\\](.*?)\\[\\/list\\]/si', 'replace' => '<ul>$1</ul>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '26', 'name' => 'code', 'example' => '[code]Html[/code]', 'pattern' => '/\\[code\\](.*?)\\[\\/code\\]/si', 'replace' => '<code>$1</code>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '28', 'name' => 'Spoiler', 'example' => '[spoiler]test[/spoiler]', 'pattern' => '/\\[spoiler\\](.*?)\\[\\/spoiler\\]/si', 'replace' => '<details><summary>Spoiler</summary>$1</details>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '29', 'name' => 'Notice', 'example' => '[notice]Hey[/notice]', 'pattern' => '/\\[notice\\](.*?)\\[\\/notice\\]/si', 'replace' => '<div style="width: 97.5%; display: inline;float: left; font-family: Verdana;font-size: 14px;background: rgba(237, 237, 237, 1);border: 1px solid rgb(224, 224, 224);box-shadow: 0px 2px 0px 0px rgb(234, 234, 234);padding: 9px;color: rgb(134, 134, 134);margin: 0px 0px 6px;border-radius: 2px;font-weight: 600;text-shadow: rgb(255, 255, 255) 0px 1px;clear: both;}  br { margin: 0; padding: 0; }"><strong>$1</strong> </div>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1547139924', 'updatedAt' => '1562538905'),
            array ('bbcodeId' => '32', 'name' => 'Quote', 'example' => '[quote]text[/quote]', 'pattern' => '/\\[quote\\](.*?)\\[\\/quote\\]/si', 'replace' => '<div class="quote">$1</div>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1547223951', 'updatedAt' => '1547223951'),
            array ('bbcodeId' => '33', 'name' => 'Beth Scared', 'example' => NULL, 'pattern' => ':beth-scared:', 'replace' => NULL, 'content' => NULL, 'isEmoji' => '1', 'isSystem' => '0', 'createdAt' => '1550694434', 'updatedAt' => '1550695009'),
            array ('bbcodeId' => '34', 'name' => 'zoidberg', 'example' => NULL, 'pattern' => ':zoidberg:', 'replace' => NULL, 'content' => NULL, 'isEmoji' => '1', 'isSystem' => '0', 'createdAt' => '1550695647', 'updatedAt' => '1550695647'),
            array ('bbcodeId' => '35', 'name' => 'breezy', 'example' => NULL, 'pattern' => ':breezy:', 'replace' => NULL, 'content' => NULL, 'isEmoji' => '1', 'isSystem' => '0', 'createdAt' => '1550695668', 'updatedAt' => '1550695668'),
            array ('bbcodeId' => '36', 'name' => 'bobthecat', 'example' => NULL, 'pattern' => ':bobthecat:', 'replace' => NULL, 'content' => NULL, 'isEmoji' => '1', 'isSystem' => '0', 'createdAt' => '1550695681', 'updatedAt' => '1550695681'),
            array ('bbcodeId' => '37', 'name' => 'fat-unicorn', 'example' => NULL, 'pattern' => ':fat-unicorn:', 'replace' => NULL, 'content' => NULL, 'isEmoji' => '1', 'isSystem' => '0', 'createdAt' => '1550695700', 'updatedAt' => '1550695700'),
            array ('bbcodeId' => '38', 'name' => 'git', 'example' => NULL, 'pattern' => ':git:', 'replace' => NULL, 'content' => NULL, 'isEmoji' => '1', 'isSystem' => '0', 'createdAt' => '1550695712', 'updatedAt' => '1550695712'),
            array ('bbcodeId' => '39', 'name' => 'morty-messedup', 'example' => NULL, 'pattern' => ':morty-messedup:', 'replace' => NULL, 'content' => NULL, 'isEmoji' => '1', 'isSystem' => '0', 'createdAt' => '1550695729', 'updatedAt' => '1550695729'),
            array ('bbcodeId' => '40', 'name' => 'nibbler', 'example' => NULL, 'pattern' => ':nibbler:', 'replace' => NULL, 'content' => NULL, 'isEmoji' => '1', 'isSystem' => '0', 'createdAt' => '1550695742', 'updatedAt' => '1550695742'),
            array ('bbcodeId' => '41', 'name' => 'overwatch-ana', 'example' => NULL, 'pattern' => ':overwatch-ana:', 'replace' => NULL, 'content' => NULL, 'isEmoji' => '1', 'isSystem' => '0', 'createdAt' => '1550695754', 'updatedAt' => '1550695754'),
            array ('bbcodeId' => '42', 'name' => 'pink-unicorn', 'example' => NULL, 'pattern' => ':pink-unicorn:', 'replace' => NULL, 'content' => NULL, 'isEmoji' => '1', 'isSystem' => '0', 'createdAt' => '1550695766', 'updatedAt' => '1550695766'),
            array ('bbcodeId' => '43', 'name' => 'rick-drinking', 'example' => NULL, 'pattern' => ':rick-drinking:', 'replace' => NULL, 'content' => NULL, 'isEmoji' => '1', 'isSystem' => '0', 'createdAt' => '1550695781', 'updatedAt' => '1550695781'),
            array ('bbcodeId' => '44', 'name' => 'Youtube', 'example' => '[youtube]M0uSnNauWJU[/youtube]', 'pattern' => '/\\[youtube\\](.*?)\\[\\/youtube\\]/si', 'replace' => '<iframe width="480" height="400" frameborder="0" src="https://www.youtube.com/embed/$1?wmode=opaque" data-youtube-id="$1" allowfullscreen=""></iframe>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '45', 'name' => 'Ol list', 'example' => '[ol]Test Text 1[/ol]', 'pattern' => '/\\[ol\\](.*?)\\[\\/ol\\]/si', 'replace' => '<ol>$1</ol>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '46', 'name' => 'orderedlistnumerical', 'example' => '[list=1]Hey[/list]', 'pattern' => '/\\[list=1\\](.*?)\\[\\/list\\]/s', 'replace' => '<ol>$1</ol>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '47', 'name' => 'unorderedlist', 'example' => '[list]Hey[/list]', 'pattern' => '/\\[list\\](.*?)\\[\\/list\\]/s', 'replace' => '<ul>$1</ul>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '48', 'name' => 'listitem', 'example' => '[*]text[/*]', 'pattern' => '/\\[\\*\\](.*?)\\[\\/\\*\\]/si', 'replace' => '<li>$1</li>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '49', 'name' => 'Horizontal Line', 'example' => '[hr]', 'pattern' => '/\\[hr\\]/si', 'replace' => '<hr />', 'content' => '', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '50', 'name' => 'Administrator Notice', 'example' => '[sitecp]My text goes here![/sitecp]', 'pattern' => '/\\[sitecp\\](.*?)\\[\\/sitecp\\]/si', 'replace' => '<div style="padding:8px 35px 8px 14px;background-color:#c66464;border:1px solid #FFFFFF;width:70%;margin: auto;color:#ffffff;"><div><strong>Administrator Message:</strong></div><div>$1</div></div>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '51', 'name' => 'Community Sitecp Notice', 'example' => '[ca]My text goes here![/ca]', 'pattern' => '/\\[ca\\](.*?)\\[\\/ca\\]/si', 'replace' => '<div style="padding:8px 35px 8px 14px;background-color:#c66464;border:1px solid #FFFFFF;width:70%;margin: auto;color:#ffffff;"><div><strong>Community Administrator Message:</strong></div><div>$1</div></div>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '52', 'name' => 'Moderator Notice', 'example' => '[mod]My text goes here![/mod]', 'pattern' => '/\\[mod\\](.*?)\\[\\/mod\\]/si', 'replace' => '<div style="padding: 8px 35px 8px 14px; background-color: #000000; border: 1px solid #FFFFFF; -webkit-border-radius: 4px; -moz-border-radius: 4px; border-radius: 4px; width:70%; color: #fff; margin: auto;"><div><strong>Moderator Message: </strong></div><div>$1</div></div>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '53', 'name' => 'Senior Staff Notice', 'example' => '[snr]My text goes here![/snr]', 'pattern' => '/\\[snr\\](.*?)\\[\\/snr\\]/si', 'replace' => '<div style="padding: 8px 35px 8px 14px; background-color: #a786af; border: 1px solid #FFFFFF; -webkit-border-radius: 4px; -moz-border-radius: 4px; border-radius: 4px; width: 70%; margin: auto;color:white;"><div><strong>Senior Message:</strong></div><div>$1</div></div>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1547139924', 'updatedAt' => '1562598880'),
            array ('bbcodeId' => '54', 'name' => 'Soundcloud Embedding', 'example' => '[soundcloud]https://soundcloud.com/forss/lux-aeterna[/soundcloud]', 'pattern' => '/\\[soundcloud\\](.*?)\\[\\/soundcloud\\]/si', 'replace' => '<iframe width="600" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=$1&auto_play=false&visual=true"></iframe>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '55', 'name' => 'Twitter Embedding', 'example' => '[tweet]883203931370926080[/tweet]', 'pattern' => '/\\[tweet\\](.*?)\\[\\/tweet\\]/si', 'replace' => '<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/thishabbo/status/$1"></a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '56', 'name' => 'Facebook Video Embedding', 'example' => '[fbvideo]https://www.facebook.com/MacRumors/videos/10155794335253923/[/fbvideo]', 'pattern' => '/\\[fbvideo\\](.*?)\\[\\/fbvideo\\]/si', 'replace' => '<iframe src="https://www.facebook.com/plugins/video.php?href=$1&show_text=1&width=560" width="560" height="401" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allowFullScreen="true"></iframe>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '57', 'name' => 'Spotify Song Embedding', 'example' => '[spotify]3tW6NhWt9RgFpZxJBWYA3U[/spotify]', 'pattern' => '/\\[spotify\\](.*?)\\[\\/spotify\\]/si', 'replace' => '<iframe src="https://open.spotify.com/embed/track/$1" width="300" height="380" frameborder="0" allowtransparency="true"></iframe>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '58', 'name' => 'Instagram Embedding', 'example' => '[instagram]Bn8dnk8A8FJ[/instagram]', 'pattern' => '/\\[instagram\\](.*?)\\[\\/instagram\\]/si', 'replace' => '<iframe src="//instagram.com/p/$1/embed/" width="612" height="710" frameborder="0" scrolling="no" allowtransparency="true"></iframe>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1547139924', 'updatedAt' => '1547139924'),
            array ('bbcodeId' => '59', 'name' => 'Jingle House Embedding', 'example' => '[jingle]163[/jingle]', 'pattern' => '/\\[jingle\\](.*?)\\[\\/jingle\\]/si', 'replace' => '<iframe width="100%" height="140" frameborder="no" scrolling="no" src="https://jingle.house/embed.php?id=$1&name=ha-connect"></iframe>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1547139924', 'updatedAt' => '1563203646'),
            array ('bbcodeId' => '60', 'name' => 'old mention', 'example' => '[mention]@nickname[/mention]', 'pattern' => '/\\[mention\\]@(.*?)\\[\\/mention\\]/si', 'replace' => '@$1', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1563815945', 'updatedAt' => '1563815945'),
            array ('bbcodeId' => '61', 'name' => 'Admin BBCode', 'example' => '[admin]My text goes here![/admin]', 'pattern' => '/\\[admin\\](.*?)\\[\\/admin\\]/si', 'replace' => '<div style="padding: 8px 35px 8px 14px; background-color: #c37070; border: 1px solid #FFFFFF; -webkit-border-radius: 4px; -moz-border-radius: 4px; border-radius: 4px; width:70%; color: #fff; margin: auto;"><div><strong>Administrator Message: </strong></div><div>$1</div></div>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1562536619', 'updatedAt' => '1562536619'),
            array ('bbcodeId' => '62', 'name' => 'Image Center', 'example' => '[imgc]http://puu.sh/DPYdE/de56ad7671.png[/imgc]', 'pattern' => '/\\[imgc\\](.*?)\\[\\/imgc\\]/si', 'replace' => '<img src="$1" style="  display: block;   margin-left: auto;   margin-right: auto;   width: 50%;">', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1562539079', 'updatedAt' => '1562539178'),
            array ('bbcodeId' => '63', 'name' => 'Developer', 'example' => '[developer]This is a test[/developer]', 'pattern' => '/\\[developer\\](.*)\\[\\/developer\\]/si', 'replace' => '<div style="padding: 8px 35px 8px 14px; background-color: #66acb1; border: 1px solid #FFFFFF; -webkit-border-radius: 4px; -moz-border-radius: 4px; border-radius: 4px; width:70%; color: #fff; margin: auto;"><div><strong>Developer Message: </strong></div><div>$1</div></div>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1562582062', 'updatedAt' => '1562582062'),
            array ('bbcodeId' => '64', 'name' => 'Manager', 'example' => '[manager]This is a test[/manager]', 'pattern' => '/\\[manager\\](.*?)\\[\\/manager\\]/si', 'replace' => '<div style="padding: 8px 35px 8px 14px; background-color: #80b481; border: 1px solid #FFFFFF; -webkit-border-radius: 4px; -moz-border-radius: 4px; border-radius: 4px; width:70%; color: #fff; margin: auto;"><div><strong>Manager Message: </strong></div><div>$1</div></div>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1562583543', 'updatedAt' => '1562583543'),
            array ('bbcodeId' => '65', 'name' => 'Video', 'example' => '[video]dQw4wp9WgXcQ[/video]', 'pattern' => '/\\[video\\](.*?)\\[\\/video\\]/si', 'replace' => '<iframe width="560" height="315" frameborder="0" src="https://www.youtube.com/embed/$1?wmode=opaque"data-youtube-id="$1" allowfullscreen=""></iframe>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1562691325', 'updatedAt' => '1562691325'),
            array ('bbcodeId' => '66', 'name' => 'Request Notice', 'example' => '[request]190[/request]', 'pattern' => '/\\[request\\](.*?)\\[\\/request\\]/si', 'replace' => '<iframe width="100%" height="140" frameborder="no" scrolling="no" src="https://jingle.house/request/embed.php?id=$1&name=ha-connect"></iframe>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1563199423', 'updatedAt' => '1563201525'),
            array ('bbcodeId' => '67', 'name' => 'Mention v2', 'example' => '@user', 'pattern' => '/@([a-zA-Z0-9]+)/si', 'replace' => '<a class="mention-user-2" data-type="internal" data-url="/user/profile/$1">$1</a>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1563813905', 'updatedAt' => '1581372558'),
            array ('bbcodeId' => '70', 'name' => 'Forum Admin Notice', 'example' => '[fa]My text goes here![/fa]', 'pattern' => '/\\[fa\\](.*?)\\[\\/fa\\]/si', 'replace' => '<div style="padding:8px 35px 8px 14px;background-color:#c66464;border:1px solid #FFFFFF;width:70%;margin: auto;color:#ffffff;"><div><strong>Forum Administrator Message:</strong></div><div>$1</div></div>', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '0', 'createdAt' => '1564227412', 'updatedAt' => '1564227412'),
            array ('bbcodeId' => '71', 'name' => 'httpToHttps', 'example' => 'no example', 'pattern' => '/http\\:\\/\\//si', 'replace' => 'https://', 'content' => '$1', 'isEmoji' => '0', 'isSystem' => '1', 'createdAt' => '1582141994', 'updatedAt' => '1582141994')
        ));
    }
}
