<?php

use Illuminate\Database\Seeder;

class ThreadsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('threads')->delete();
        
        \DB::table('threads')->insert(array (
            0 => 
            array (
                'threadId' => 1,
                'categoryId' => 2,
                'title' => 'VX Ongoing!',
                'isOpen' => 0,
                'isDeleted' => 0,
                'posts' => 2,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 1,
                'lastPostId' => 21,
                'isSticky' => 0,
                'prefixId' => 1,
                'createdAt' => 1538578022,
                'updatedAt' => 1551996694,
            ),
            1 => 
            array (
                'threadId' => 2,
                'categoryId' => 3,
                'title' => 'New test data',
                'isOpen' => 0,
                'isDeleted' => 0,
                'posts' => 3,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 2,
                'lastPostId' => 23,
                'isSticky' => 0,
                'prefixId' => 1,
                'createdAt' => 1538578022,
                'updatedAt' => 1552092125,
            ),
            2 => 
            array (
                'threadId' => 3,
                'categoryId' => 6,
                'title' => 'Birthday Badge',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 5,
                'lastPostId' => 5,
                'isSticky' => 0,
                'prefixId' => 1,
                'createdAt' => 1538578022,
                'updatedAt' => 1538578022,
            ),
            3 => 
            array (
                'threadId' => 4,
                'categoryId' => 7,
                'title' => 'Welcome test!',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 6,
                'lastPostId' => 6,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538578022,
                'updatedAt' => 1538578022,
            ),
            4 => 
            array (
                'threadId' => 5,
                'categoryId' => 6,
                'title' => 'Test #1',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 7,
                'lastPostId' => 7,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538672652,
                'updatedAt' => 1538672652,
            ),
            5 => 
            array (
                'threadId' => 6,
                'categoryId' => 6,
                'title' => 'Test #2',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 8,
                'lastPostId' => 8,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538672679,
                'updatedAt' => 1538672679,
            ),
            6 => 
            array (
                'threadId' => 7,
                'categoryId' => 6,
                'title' => 'Test #3',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 9,
                'lastPostId' => 9,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538672712,
                'updatedAt' => 1538672712,
            ),
            7 => 
            array (
                'threadId' => 8,
                'categoryId' => 6,
                'title' => 'Test #4',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 10,
                'lastPostId' => 10,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538672751,
                'updatedAt' => 1538672751,
            ),
            8 => 
            array (
                'threadId' => 9,
                'categoryId' => 6,
                'title' => 'Test #5',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 11,
                'lastPostId' => 11,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538672783,
                'updatedAt' => 1538672783,
            ),
            9 => 
            array (
                'threadId' => 10,
                'categoryId' => 5,
                'title' => 'Test #1',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 12,
                'lastPostId' => 12,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538715429,
                'updatedAt' => 1538715429,
            ),
            10 => 
            array (
                'threadId' => 11,
                'categoryId' => 5,
                'title' => 'Test #2',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 13,
                'lastPostId' => 13,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538715447,
                'updatedAt' => 1538715447,
            ),
            11 => 
            array (
                'threadId' => 12,
                'categoryId' => 5,
                'title' => 'Test #3',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 14,
                'lastPostId' => 14,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538715462,
                'updatedAt' => 1538715462,
            ),
            12 => 
            array (
                'threadId' => 13,
                'categoryId' => 5,
                'title' => 'Test #4',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 15,
                'lastPostId' => 15,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538715477,
                'updatedAt' => 1538715477,
            ),
            13 => 
            array (
                'threadId' => 14,
                'categoryId' => 5,
                'title' => 'Test #5',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 16,
                'lastPostId' => 16,
                'isSticky' => 0,
                'prefixId' => 1,
                'createdAt' => 1538715493,
                'updatedAt' => 1538717246,
            ),
            14 => 
            array (
                'threadId' => 15,
                'categoryId' => 9,
                'title' => 'Report by test',
                'isOpen' => 1,
                'isDeleted' => 1,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 2,
                'firstPostId' => 17,
                'lastPostId' => 17,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1547223025,
                'updatedAt' => 1547223728,
            ),
            15 => 
            array (
                'threadId' => 16,
                'categoryId' => 9,
                'title' => 'Report by test',
                'isOpen' => 1,
                'isDeleted' => 1,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 2,
                'firstPostId' => 18,
                'lastPostId' => 18,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1547223151,
                'updatedAt' => 1547223721,
            ),
            16 => 
            array (
                'threadId' => 17,
                'categoryId' => 9,
                'title' => 'Report by test',
                'isOpen' => 1,
                'isDeleted' => 1,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 2,
                'firstPostId' => 19,
                'lastPostId' => 19,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1547223372,
                'updatedAt' => 1547223716,
            ),
            17 => 
            array (
                'threadId' => 18,
                'categoryId' => 10,
                'title' => 'Report by test',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 2,
                'firstPostId' => 20,
                'lastPostId' => 20,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1547223761,
                'updatedAt' => 1547223761,
            ),
            18 => 
            array (
                'threadId' => 19,
                'categoryId' => 6,
                'title' => 'Eurovision Poll 2018',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 1,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 24,
                'lastPostId' => 24,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1552144959,
                'updatedAt' => 1552144959,
            ),
            19 => 
            array (
                'threadId' => 20,
                'categoryId' => 6,
                'title' => 'Eurovision Poll',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 1,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 25,
                'lastPostId' => 25,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1552145019,
                'updatedAt' => 1552145019,
            ),
            20 => 
            array (
                'threadId' => 21,
                'categoryId' => 6,
                'title' => 'Eurovision Poll',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 1,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 26,
                'lastPostId' => 26,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1552145036,
                'updatedAt' => 1552145036,
            ),
            21 => 
            array (
                'threadId' => 22,
                'categoryId' => 6,
                'title' => 'Eurovision Poll',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 1,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 27,
                'lastPostId' => 27,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1552145054,
                'updatedAt' => 1552145054,
            ),
            22 => 
            array (
                'threadId' => 23,
                'categoryId' => 6,
                'title' => 'Eurovision Poll',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 1,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 28,
                'lastPostId' => 28,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1552145118,
                'updatedAt' => 1552145118,
            ),
            23 => 
            array (
                'threadId' => 24,
                'categoryId' => 6,
                'title' => 'Eurovision Poll',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 1,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 29,
                'lastPostId' => 29,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1552145142,
                'updatedAt' => 1552145142,
            ),
            24 => 
            array (
                'threadId' => 25,
                'categoryId' => 5,
                'title' => 'Test Article!',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 1,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 30,
                'lastPostId' => 30,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1552148604,
                'updatedAt' => 1552148604,
            ),
            25 => 
            array (
                'threadId' => 26,
                'categoryId' => 5,
                'title' => 'Test 2!',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 1,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 31,
                'lastPostId' => 31,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1552148621,
                'updatedAt' => 1552148621,
            ),
            26 => 
            array (
                'threadId' => 27,
                'categoryId' => 5,
                'title' => 'Test 4!',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 1,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 32,
                'lastPostId' => 32,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1552148637,
                'updatedAt' => 1552148637,
            ),
            27 => 
            array (
                'threadId' => 28,
                'categoryId' => 5,
                'title' => 'Test 5!',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 1,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 33,
                'lastPostId' => 33,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1552148663,
                'updatedAt' => 1552148663,
            ),
            28 => 
            array (
                'threadId' => 29,
                'categoryId' => 5,
                'title' => 'Test 7!',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 1,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 34,
                'lastPostId' => 34,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1552148693,
                'updatedAt' => 1552148693,
            ),
        ));
        
        
    }
}