<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ThreadsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('threads')->delete();
        DB::table('threads')->insert(array (
            0 =>
            array (
                'threadId' => 1,
                'categoryId' => 2,
                'title' => 'VX Ongoing!',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 1,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 1,
                'lastPostId' => 3,
                'isSticky' => 0,
                'prefixId' => 1,
                'createdAt' => 1538578022,
                'updatedAt' => 1538578022,
            ),
            1 =>
            array (
                'threadId' => 2,
                'categoryId' => 3,
                'title' => 'New test data',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 1,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 2,
                'lastPostId' => 4,
                'isSticky' => 0,
                'prefixId' => 1,
                'createdAt' => 1538578022,
                'updatedAt' => 1538578022,
            ),
            2 =>
            array (
                'threadId' => 3,
                'categoryId' => 6,
                'title' => 'Birthday Badge',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 5,
                'lastPostId' => 5,
                'isSticky' => 0,
                'prefixId' => 1,
                'createdAt' => 1538578022,
                'updatedAt' => 1538578022,
            ),
            3 =>
            array (
                'threadId' => 4,
                'categoryId' => 7,
                'title' => 'Welcome test!',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 6,
                'lastPostId' => 6,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538578022,
                'updatedAt' => 1538578022,
            ),
            4 =>
            array (
                'threadId' => 5,
                'categoryId' => 6,
                'title' => 'Test #1',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 7,
                'lastPostId' => 7,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538672652,
                'updatedAt' => 1538672652,
            ),
            5 =>
            array (
                'threadId' => 6,
                'categoryId' => 6,
                'title' => 'Test #2',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 8,
                'lastPostId' => 8,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538672679,
                'updatedAt' => 1538672679,
            ),
            6 =>
            array (
                'threadId' => 7,
                'categoryId' => 6,
                'title' => 'Test #3',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 9,
                'lastPostId' => 9,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538672712,
                'updatedAt' => 1538672712,
            ),
            7 =>
            array (
                'threadId' => 8,
                'categoryId' => 6,
                'title' => 'Test #4',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 10,
                'lastPostId' => 10,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538672751,
                'updatedAt' => 1538672751,
            ),
            8 =>
            array (
                'threadId' => 9,
                'categoryId' => 6,
                'title' => 'Test #5',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 11,
                'lastPostId' => 11,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538672783,
                'updatedAt' => 1538672783,
            ),
            9 =>
            array (
                'threadId' => 10,
                'categoryId' => 5,
                'title' => 'Test #1',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 12,
                'lastPostId' => 12,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538715429,
                'updatedAt' => 1538715429,
            ),
            10 =>
            array (
                'threadId' => 11,
                'categoryId' => 5,
                'title' => 'Test #2',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 13,
                'lastPostId' => 13,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538715447,
                'updatedAt' => 1538715447,
            ),
            11 =>
            array (
                'threadId' => 12,
                'categoryId' => 5,
                'title' => 'Test #3',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 14,
                'lastPostId' => 14,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538715462,
                'updatedAt' => 1538715462,
            ),
            12 =>
            array (
                'threadId' => 13,
                'categoryId' => 5,
                'title' => 'Test #4',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 15,
                'lastPostId' => 15,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1538715477,
                'updatedAt' => 1538715477,
            ),
            13 =>
            array (
                'threadId' => 14,
                'categoryId' => 5,
                'title' => 'Test #5',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 1,
                'firstPostId' => 16,
                'lastPostId' => 16,
                'isSticky' => 0,
                'prefixId' => 1,
                'createdAt' => 1538715493,
                'updatedAt' => 1538717246,
            ),
            14 =>
            array (
                'threadId' => 15,
                'categoryId' => 9,
                'title' => 'Report by test',
                'isOpen' => 1,
                'isDeleted' => 1,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 2,
                'firstPostId' => 17,
                'lastPostId' => 17,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1547223025,
                'updatedAt' => 1547223728,
            ),
            15 =>
            array (
                'threadId' => 16,
                'categoryId' => 9,
                'title' => 'Report by test',
                'isOpen' => 1,
                'isDeleted' => 1,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 2,
                'firstPostId' => 18,
                'lastPostId' => 18,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1547223151,
                'updatedAt' => 1547223721,
            ),
            16 =>
            array (
                'threadId' => 17,
                'categoryId' => 9,
                'title' => 'Report by test',
                'isOpen' => 1,
                'isDeleted' => 1,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 2,
                'firstPostId' => 19,
                'lastPostId' => 19,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1547223372,
                'updatedAt' => 1547223716,
            ),
            17 =>
            array (
                'threadId' => 18,
                'categoryId' => 10,
                'title' => 'Report by test',
                'isOpen' => 1,
                'isDeleted' => 0,
                'posts' => 0,
                'views' => 0,
                'isApproved' => 1,
                'userId' => 2,
                'firstPostId' => 20,
                'lastPostId' => 20,
                'isSticky' => 0,
                'prefixId' => 0,
                'createdAt' => 1547223761,
                'updatedAt' => 1547223761,
            ),
        ));
    }
}
